saagie/api-saagie

saagieapi/projects/gql_template.py, saagieapi/projects/saagie_api.py, tests/test_projects.py
=> 🚑  add create pipeline and get instance pipeline info

saagieapi/projects/saagie_api.py
=> 🚑 add easy connect method

saagieapi/projects/saagie_api.py
=> :bug: fixing extra technology name

saagieapi/projects/gql_template.py, saagieapi/projects/saagie_api.py, tests/test_projects.py, tests/test_projects_integration.py
Resolves #19 
label has also been removed for every technology document
=> Issue 19 : catalog can now be specified when creating a job

tests/test_projects_integration.py
=> Improving integration tests timeout on project creation

README.md, saagieapi/projects/gql_template.py, saagieapi/projects/saagie_api.py, tests/schema.graphqls, tests/test_projects.py
Change schema.graphqls in test  (in order to use the one updated at Nov 10, 2021)
=> :sparkles: change the file schema.graphqls 

poetry.lock, pyproject.toml, saagieapi/projects/gql_template.py, saagieapi/projects/saagie_api.py, tests/test_projects.py
close #44 
(pipeline not implemented, waiting for refactoring since complexe pipeline is now available)
=>  ⚡ Add scheduling feature for jobs

saagieapi/projects/gql_template.py, saagieapi/projects/saagie_api.py, tests/test_projects.py
=> :zap: Add CPU/RAM limit and timezone scheduling per job

saagieapi/projects/gql_template.py, saagieapi/projects/saagie_api.py, tests/test_projects.py
=> :zap: Add the ability to upgrade a job

saagieapi/projects/gql_template.py, saagieapi/projects/graph_pipeline.py, saagieapi/projects/saagie_api.py, tests/test_projects.py, tests/test_projects_integration.py
=> 🥚 Add graph pipelines creation, deletion, upgrade, edit

saagieapi/projects/saagie_api.py
=> :penguin: Add ability to get pipeline ID by name

saagieapi/projects/__init__.py, saagieapi/projects/saagie_api.py, tests/test_projects_integration.py
=> :green_apple: Add ability to get project ID by name

saagieapi/projects/gql_template.py, saagieapi/projects/saagie_api.py, tests/test_projects.py, tests/test_projects_integration.py
=> :bug: Change edit_job and edit_pipeline

saagieapi/projects/gql_template.py, saagieapi/projects/saagie_api.py, tests/test_projects.py, tests/test_projects_integration.py
This reverts commit 32bfe364dcca89f81e70066e43b91441d4da69d5.
=> Revert "Fix edit_job and edit_pipeline"

saagieapi/projects/gql_template.py, saagieapi/projects/saagie_api.py, tests/test_projects.py, tests/test_projects_integration.py
=> :bug: Fix edit_job and edit_pipeline

poetry.lock, pyproject.toml
Upgrading dependencies (pytz it too old and generates conflicts when adding saagie-api in Jupyterlab)
=> Upgrading dependencies

saagieapi/projects/saagie_api.py
=> :zap: add number of retries as paramater

poetry.lock, pyproject.toml, saagieapi/projects/gql_template.py, saagieapi/projects/saagie_api.py, tests/test_projects.py, tests/test_projects_integration.py
Use gql3 instead of requests and add alerting in creation of job
close #52
=> :chart_with_upwards_trend: GQL3

poetry.lock, pyproject.toml, saagieapi/projects/saagie_api.py
=> :zap: add requests_toolbelt as dependencies

poetry.lock, pyproject.toml, saagieapi/projects/gql_template.py, saagieapi/projects/saagie_api.py, tests/test_projects_integration.py
=> Adding depreciation warnings

saagieapi/projects/gql_template.py, saagieapi/projects/saagie_api.py, tests/test_projects.py
=> :green_apple: Add functions of docker credentials

saagieapi/projects/saagie_api.py
=> Removing unused format in gql query

README.md
Fixed linting and typos in Readme
=> Fixed linting and typos in Readme

saagieapi/apps/apps.py, saagieapi/docker_credentials/docker_credentials.py, saagieapi/env_vars/env_vars.py, saagieapi/jobs/jobs.py, saagieapi/pipelines/pipelines.py, saagieapi/projects/projects.py, saagieapi/saagie_api.py, saagieapi/utils/bearer_auth.py, saagieapi/utils/gql_client.py
Fixes #94 
Automatically renew auth token when expired (happens for instance with a long job launched with  `jobs.run_with_callback` )
=> :bug: Fixing auth token expiration

saagieapi/pipelines/gql_queries.py, saagieapi/pipelines/pipelines.py
=> :wheelchair: get instance information for get_pipeline

poetry.lock, pyproject.toml, saagieapi/apps/apps.py, saagieapi/docker_credentials/docker_credentials.py, saagieapi/env_vars/env_vars.py, saagieapi/jobs/jobs.py, saagieapi/pipelines/pipelines.py, saagieapi/projects/projects.py, saagieapi/saagie_api.py, saagieapi/utils/bearer_auth.py, saagieapi/utils/gql_client.py, saagieapi/utils/rich_console.py, tests/unit/saagie_api_unit_test.py
=> ♿  Chore/improve logging

saagieapi/apps/apps.py, saagieapi/docker_credentials/docker_credentials.py, saagieapi/env_vars/env_vars.py, saagieapi/jobs/jobs.py, saagieapi/pipelines/pipelines.py, saagieapi/projects/projects.py, saagieapi/saagie_api.py, saagieapi/utils/gql_client.py
=> :wheelchair: chore: Uniform and configurable pprint parameter

saagieapi/projects/projects.py, tests/integration/saagie_api_integration_test.py, tests/unit/projects_unit_test.py
=> You can now specify multiple groups and roles when creating a project

saagieapi/apps/apps.py, saagieapi/apps/gql_queries.py, saagieapi/env_vars/env_vars.py, saagieapi/jobs/gql_queries.py, saagieapi/jobs/jobs.py, saagieapi/pipelines/gql_queries.py, saagieapi/pipelines/pipelines.py, saagieapi/projects/projects.py, saagieapi/saagie_api.py, saagieapi/utils/folder_functions.py, saagieapi/utils/gql_client.py, tests/integration/saagie_api_integration_test.py, tests/unit/apps_unit_test.py
Add export of app, environment variables, jobs, pipelines and project
=> Add export functions

saagieapi/gql_queries.py, tests/integration/saagie_api_integration_test.py
=> Fixing Spark job creation

saagieapi/jobs/jobs.py
=> 🐛  check runtime using ID instead label

saagieapi/jobs/jobs.py, tests/integration/saagie_api_integration_test.py
Add feature create or upgrade for jobs mentioned in #116
=> :bug: Feature/create or update

saagieapi/pipelines/pipelines.py, tests/integration/pipelines_integration_test.py, tests/integration/resources/import/pipeline/pipeline_without_alerting.json
* correct import from json for pipeline without alerting
=> :bug: correct pipeline import from json

saagieapi/apps/apps.py, tests/integration/apps_integration_test.py
=> :bug: fix app edit and app export 

saagieapi/env_vars/env_vars.py, tests/integration/env_vars_integration_test.py
=> :bug: fix create_or_update env var for project

saagieapi/env_vars/env_vars.py
=> :bug: fix env var export

saagieapi/apps/gql_queries.py
=> :bug: add __type_name of app event

saagieapi/projects/projects.py
=> Fix groups_and_role behaviour

.github/workflows/build-and-test-pr.yml, saagieapi/jobs/jobs.py, saagieapi/projects/projects.py
Correct import from json for jobs
=> :bug:  Fix/import from json

saagieapi/projects/projects.py, tests/integration/apps_integration_test.py, tests/integration/conftest.py, tests/integration/groups_integration_test.py, tests/integration/jobs_integration_test.py, tests/integration/pipelines_integration_test.py, tests/integration/projects_integration_test.py, tests/integration/saagie_api_integration_test.py, tests/unit/apps_unit_test.py, tests/unit/env_vars_unit_test.py, tests/unit/jobs_unit_test.py, tests/unit/pipelines_unit_test.py, tests/unit/saagie_api_unit_test.py
Correct the rights parameters verification given to the project creation ( Fix #182 )
=> :bug:  Fix/project rights

docs/Jobs/create_or_upgrade_job.rst, saagieapi/jobs/jobs.py, tests/integration/conftest.py, tests/integration/jobs_integration_test.py
fix #187 
- Fix the function `create_or_upgrade` in order to support create or upgrade job that doesn't have artefact
=> :bug: change create_or_upgrade_job

saagieapi/env_vars/env_vars.py, tests/integration/env_vars_integration_test.py
=> 🐛 Add env_vars.get to get env var information

saagieapi/jobs/jobs.py, tests/integration/conftest.py
Fix `create ` function in `jobs.py`
=> :bug: fix creation of job
